<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta charset="utf-8">
<title>Jeito de Moça - Sistema v1.0</title>
<base href="<?php echo site_url() ?>"/>
<link rel="icon" href="img/favicon.ico">
<style>
body {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 13px;
    line-height: 1.42857143;
    color: #333;
    background-color: #fff;
    margin: 0;
}

td{padding:2px}
th{padding:5px}
th.titulo{background:#f0f0f0;padding:7px}
p.obs{color:#999;font-style:italic}
td.borda{border-bottom:1px solid #c0c0c0}
</style>
</head>
<body>
        
    <table>
        <tr>
            <td height="120">
            <table width="100%" height="200">
                <tr>
                <?php if($cliente['cliente']): ?>
                    <td valign="top">
                        <?php echo $cliente['cliente']; ?><br>
                        <?php echo $cliente['email']; ?><br>
                        <?php echo $cliente['telefone']; ?><br>
                        <?php echo $cliente['origem']; ?>
                    <td>
                <?php endif; ?>
                        
                <?php if($cliente['endereco']): ?>
                    <td valign="top">
                        <?php echo $cliente['endereco']; ?>, <?php echo $cliente['numero']; ?><br>
                        <?php echo $cliente['complemento'] ? $cliente['complemento'] . '<br>' : '' ; ?>
                        <?php echo $cliente['bairro']; ?><br>
                        <?php echo $cliente['cep']; ?> - <?php echo $cliente['cidade']; ?>, <?php echo $cliente['estado']; ?>
                    </td>
                <?php endif; ?>
                    <td align="right" valign="top">
                        <img src="img/logo-login.png"/>
                    </td>
                </tr>        
            </table>
            </td>
        </tr>        
    </table>
    <?php $c = 0; foreach ($pedidos as $status => $dados):  $c++; ?>
    <table width="100%">
      
      <?php $total = 0; foreach ($dados as $dado): $total += $dado['subtotal']; ?>
      <thead>
            <tr>
                  <th class="titulo" colspan="5">
                    <table>
                        <tr>
                            <td align="left">#<?php echo $dado['id'] ?></td>
                            <td align="right"><?php echo date('d/m/Y H:i:s', strtotime($dado['data'])) ?></td>
                        </tr>
                    </table>
                  </th>
            </tr>
            <tr>
                <th>Item</th>
                <th>Cordão</th>
                <th>Banho</th>
                <th>Qtd.</th>
                <th>Valor (R$)</th>
            </tr>
            <tr>
                <td colspan="5" class="borda"></td>
            </tr> 
        </thead>
      <tbody>
      <?php if(!empty($dado['itens'])): ?>
      
      <?php foreach ($dado['itens'] as $item): ?>
      
      <?php if($item['tipo'] == 'Produto'): ?>
            <tr>
                  <td><?php echo $item['item'] ?></td>
                  <td><?php echo $item['cordao'] ? $item['cordao'] .' cm' : '--' ?></td>
                  <td><?php echo $item['banho'] ?></td>
                  <td><?php echo $item['quantidade'] ?></td>
                  <td width="100"><?php echo number_format($item['valor'] * $item['quantidade'], 2, ',', '.') ?></td>
            </tr>
            <tr>
                <td colspan="5" class="borda"></td>
            </tr> 
      <?php endif ?>
      
      <?php if($item['tipo'] == 'Encargo'): ?>
            <tr>
                  <td colspan="4" align="right"><i>Encargo / <?php echo $item['item'] ?>:</i></td>
                  <td><i>-<?php echo number_format($item['valor'], 2, ',', '.') ?><i></td>
            </tr>
            <tr>
                <td colspan="5" class="borda"></td>
            </tr> 
      <?php endif ?>
      
      <?php endforeach ?>
      
      <?php endif ?>      
      
      <?php if(!empty($dado['subtotal'])): ?>
            <tr>
                  <td colspan="4" align="right"><strong>Subtotal:</strong></td>
                  <td><strong><?php echo number_format($dado['subtotal'], 2, ',', '.') ?></strong></td>
            </tr>
      <?php endif ?>
      
      <?php if(!empty($dado['empresas'])): ?>
            <tr>
                  <td colspan="5"><strong>Fornecedores:</strong>
                        <?php $c = 0; foreach ($dado['empresas'] as $fornecedor): $c++; ?>
                        <?php echo $fornecedor['empresa']; ?><?php echo $c == count($dado['empresas']) ? '.' : ', ' ?>
                        <?php endforeach ?>                        
                  </td>                  
            </tr>
      <?php endif ?>
      
      <?php if(!empty($dado['postagem'])): ?>
            <tr>
                  <td colspan="5"><strong>Postagem:</strong>
                        <?php echo $dado['postagem'] ?>
                        <?php echo $dado['rastreio'] ? '('. $dado['rastreio'] .')' : '' ?>
                  </td>                  
            </tr>
      <?php endif ?>
      
      </tbody>
      <?php endforeach ?>
      
      <?php if(!empty($total) && $total > 0): ?>
      <tbody>
            <tr>
                  <td colspan="4" align="right"><strong>Total Geral:</strong></td>
                  <td><strong><?php echo number_format($total, 2, ',', '.') ?></strong></td>
            </tr>
      </tbody>
      <?php endif ?>
            
      </table>
    
    <?php endforeach ?>

  </body>
</html>