<div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
            <li class="active"><a href="pedidos/listar-pedidos">Listar Pedidos</a></li>
            <li><a href="pedidos/adicionar-pedido">Adicionar Pedido</a></li>
        </ul>          
      </div>
              
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Editar Pedido (<?php echo $cliente['cliente'] ?>)
        <?php if(!$this->input->post()): ?>
        <div class="pull-right">
          <a class="btn btn-default" href="javascript:history.back()" role="button"><span class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span><span class="desc">Voltar</span></a>
        </div>
        <div class="clearfix"></div>
        <?php endif ?>
        </h1>
        <?php if (validation_errors()): ?>
          <div class="alert alert-danger" role="alert">
            <strong>Hmmm!</strong> Alguns erros foram encontrados...
          </div>
          <?php endif ?>
        
          <form action="pedidos/editar-pedido/<?php echo $pid ?>" name="fpedido" id="fpedido" method="Post" enctype="multipart/form-data">
		  <?php if (count($estoques > 0)): ?>
          <div class="table-responsive">
              <table class="table">
                  <thead>
                      <tr>
                          <th class="titulo" colspan="6">Itens do Pedido</th>
                      </tr>                    
                      <tr>
                          <th width="25"><a href="javascript:void(0)"><span class="glyphicon glyphicon-question-sign" aria-hidden="true" data-toggle="popover" title="Ajuda" data-content="Marque o produto abaixo que deseja incluir e sua quantidade ao final da linha"></span></a></th>
                          <th width="125">Código</th>
                          <th width="125">Modelo</th>
                          <th>Descrição</th>
							<th width="125">Valor</th>						  
                          <th width="125">Qtd.</th>     
                      </tr>
                  </thead>
<!--<pre><?php print_r($pedido) ?></pre>                  				  -->
				  <tbody>
                    <?php $i=0; foreach ($estoques as $estoque): ?>
					<tr>						
						<td><input type="checkbox" name="ids[]" value="<?php echo $estoque['id']; ?>" <?php echo ($estoque['id'] == @$pedido['itens'][$i]['item']) ? 'checked="checked"':'' ?>></td>						
						<td><?php echo $estoque['codigo']; ?></td>
						<td><?php echo $estoque['modelo']; ?></td>
						<td><?php echo $estoque['descricao']; ?></td>
						<td>R$ <?php echo number_format($estoque['valor'], 2, ',', '') ?></td>
						</td>						
						<td><input type="number" class="form-control" name="qtd_<?php echo $estoque['id']; ?>" id="qtd_<?php echo $estoque['id']; ?>" placeholder="0" value="<?php echo set_value('quantidade[]', @$pedido['itens'][$i]['quantidade']) ?>"></td>
					</tr>                                          
					<?php $i++; endforeach; ?>                    

                  </tbody>
                  
				  
				  
				  <thead>
                    <tr>
                        <th class="titulo" colspan="6">Encargos / Taxas</th>
                    </tr>
                  </thead>
                  <tbody>                      
                      <tr>
                          <td colspan="4"></td>
                          
                          <td align="right"><strong>R$</strong></td>
                          <td>
                            <?php if(!empty($pedido['encargo'])): ?>
								<?php foreach ($pedido['encargo'] as $encargo): ?>
									<?php if($encargo['item'] == 'Valor (R$)'): ?>
										<input type="hidden" name="encargo_valor_id" value="<?php echo $encargo['id'] ?>">
										<input type="text" class="form-control valor" name="encargo_valor" placeholder="0,00" value="<?php echo set_value('encargo_valor', number_format($encargo['valor'], 2, ',', '.')) ?>">
									<?php else: ?>
										<input type="text" class="form-control valor" name="encargo_valor" placeholder="0,00" value="<?php echo set_value('encargo_valor') ?>">									
									<?php endif ?>
								<?php endforeach ?>
                            <?php endif ?>
                          </td>
                      </tr>

                      <tr>
                          <td colspan="4"></td>
                          <td align="right"><strong>%</strong></td>
                          <td>
                            <?php if(!empty($pedido['encargo'])): ?>
								<?php foreach ($pedido['encargo'] as $encargo): ?>
									<?php if($encargo['item'] == 'Percentual (%)'): ?>
									<	input type="hidden" name="encargo_percentual_id" value="<?php echo $encargo['id'] ?>">
										<input type="text" class="form-control valor" name="encargo_percentual" placeholder="0,00" value="<?php echo set_value('encargo_percentual', number_format($encargo['valor'], 2, ',', '.')) ?>">
									<?php else: ?>
										<input type="text" class="form-control valor" name="encargo_percentual" placeholder="0,00" value="<?php echo set_value('encargo_percentual') ?>">									
									<?php endif ?>
								<?php endforeach ?>
                            <?php endif ?>
                          </td>
                      </tr>                   
                  </tbody>
              </table>
          </div>
          
          <div class="row">
            <div class="col-md-3">
                <div class="form-group<?php echo form_error('postagem') ? ' has-error' : '' ?>">
                    <label for="postagem">Entrega</label>                  
                    <select name="postagem" class="form-control">
                        <option value=""<?php echo set_select('postagem', '', (empty($pedido['postagem']) ? true : false)) ?>>- Selecione -</option>
                        <option value="Sedex"<?php echo set_select('postagem', 'Sedex', ($pedido['postagem'] == 'Sedex' ? true : false)) ?>>Sedex</option>
                        <option value="Sedex10"<?php echo set_select('postagem', 'Sedex10', ($pedido['postagem'] == 'Sedex10' ? true : false)) ?>>Sedex10</option>
                        <option value="SedexHoje"<?php echo set_select('postagem', 'SedexHoje', ($pedido['postagem'] == 'SedexHoje' ? true : false)) ?>>Sedex Hoje</option>
                        <option value="PAC"<?php echo set_select('postagem', 'PAC', ($pedido['postagem'] == 'PAC' ? true : false)) ?>>PAC</option>
                        <option value="Carta Registrada"<?php echo set_select('postagem', 'Carta Registrada', ($pedido['postagem'] == 'Carta Registrada' ? true : false)) ?>>Carta Registrada</option>
						<option value="Retira"<?php echo set_select('postagem', 'Retira', ($pedido['postagem'] == 'Retira' ? true : false)) ?>>Retira</option>
						<option value="Entrega"<?php echo set_select('postagem', 'Entrega', ($pedido['postagem'] == 'Entrega' ? true : false)) ?>>Entrega</option>						
                    </select>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="rastreio">Rastreio</label>       
                    <input type="text" class="form-control" name="rastreio" value="<?php echo set_value('rastreio', $pedido['rastreio']) ?>">
                </div>
            </div>
          </div>
          
          <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                      <label for="data">Data</label>       
                      <input type="text" class="form-control mask-data" name="data" value="<?php echo set_value('data', date('d/m/Y', strtotime($pedido['data']))) ?>">
                 </div>
            </div>
            <div class="col-md-3">
                <div class="form-group<?php echo form_error('status') ? ' has-error' : '' ?>">
                    <label for="status">Status</label>                  
                    <select name="status" class="form-control">
                        <option value="Pendente"<?php echo set_select('status', 'Pendente', ($pedido['status'] == 'Pendente' ? true : false)) ?>>Pendente</option>
                        <option value="Produção"<?php echo set_select('status', 'Produção', ($pedido['status'] == 'Produção' ? true : false)) ?>>Produção</option>
                        <option value="Enviado"<?php echo set_select('status', 'Enviado', ($pedido['status'] == 'Enviado' ? true : false)) ?>>Enviado</option>
                        <option value="Concluído"<?php echo set_select('status', 'Concluído', ($pedido['status'] == 'Concluído' ? true : false)) ?>>Concluído</option>
                        <option value="Cancelado"<?php echo set_select('status', 'Cancelado', ($pedido['status'] == 'Cancelado' ? true : false)) ?>>Cancelado</option>
                    </select>
                </div>
            </div>
          </div>
          <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>Salvar</button>
            
          </form>
		  <?php endif ?>
      </div>
    </div>
  </div>