<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Corpsystem - Sistema v1.0</title>
    <base href="<?php echo site_url() ?>"/>
    <link rel="icon" href="img/favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/login.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if IE]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->      
  </head>
  <body>

    <div class="container">

    <?php if (validation_errors()): ?>
    <div class="alert alert-danger" role="alert">
      <strong>Hmmm!</strong> Os dados informados estão incorretos...
    </div>
    <?php endif ?>
    
      <form action="" method="Post" class="form-signin">
        <h2 class="form-signin-heading"><img src="img/logo-login.png"/ width="300" height="67"></h2>
        <label for="usuario" class="sr-only">Usuário</label>
        <input type="text" name="usuario" id="usuario" class="form-control" value="<?php echo set_value('usuario') ?>" placeholder="usuario" required autofocus>
        <label for="senha" class="sr-only">Senha</label>
        <input type="password" name="senha" id="senha" class="form-control" placeholder="senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug 
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>-->
  </body>
</html>
