<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="clientes">Listar Clientes <span class="sr-only">(atual)</span></a></li>
            <li><a href="clientes/adicionar-cliente">Adicionar Cliente</a></li>
          </ul>          
        </div>
        
        
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Clientes
          <div class="pull-right">
            <a class="btn btn-success" href="clientes/adicionar-cliente" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="desc">Adicionar Cliente</span></a>
          </div>
          <div class="clearfix"></div>
          </h1>
          
          <?php if ($this->session->flashdata('sucesso')): ?>
          <div class="alert alert-success" role="alert">
            <strong>Uhuuu!</strong> <?php echo $this->session->flashdata('sucesso'); ?>
          </div>
          <?php endif ?>
          
          <ul class="nav nav-tabs">
            <li role="presentation"<?php echo $status == 'ativos' ? ' class="active"' : '' ?>><a href="clientes/">Ativos</a></li>
            <li role="presentation"<?php echo $status == 'inativos' ? ' class="active"' : '' ?>><a href="clientes/listar-clientes/inativos">Inativos</a></li>
            <li role="presentation"<?php echo $status == 'todos' ? ' class="active"' : '' ?>><a href="clientes/listar-clientes/todos">Todos</a></li>
          </ul>
          
          <?php if (count($clientes) > 0): ?>
          
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th><a href="clientes/ordenar-cliente/<?php echo $status ?>/<?php echo $pagina ?>/id">N.<?php echo !empty($ordem['cliente']) && $ordem['cliente'] == 'id' ? ' <span class="caret"></span>' : '' ?></a></th>
                  <th><a href="clientes/ordenar-cliente/<?php echo $status ?>/<?php echo $pagina ?>/cliente">Cliente<?php echo !empty($ordem['cliente']) && $ordem['cliente'] == 'cliente' ? ' <span class="caret"></span>' : '' ?></a></th>
                  <th>E-mail</th>
                  <th>Telefone</th>
                  <th>CEP</th>
                  <th><a href="clientes/ordenar-cliente/<?php echo $status ?>/<?php echo $pagina ?>/data">Data<?php echo !empty($ordem['cliente']) && $ordem['cliente'] == 'data' ? ' <span class="caret"></span>' : '' ?></a></th>
                  <?php if ($status == 'todos'): ?>
                  <th>Status</th>
                  <?php endif ?>
                  <th class="opcoes">Opções</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach ($clientes as $cliente): ?>
                <tr>
                    <td><?php echo $cliente['id'] ?></td>
					<td><?php echo $cliente['cliente'] ?></td>
					<td><?php echo $cliente['email'] ? $cliente['email'] : '--' ?></td>
					<td><?php echo $cliente['telefone'] ? $cliente['telefone'] : '--'  ?></td>
					<td><?php echo $cliente['cep'] ? $cliente['cep'] : '--'  ?></td>                   
					<td><?php echo date('d/m/Y', strtotime($cliente['data'])) ?></td>
					<?php if ($status == 'todos'): ?>
					<td><?php echo $cliente['status'] ?></td>
					<?php endif ?>
					<td class="opcoes">
					<?php if($this->session->userdata('nivel') == 'Administrador' || $this->session->userdata('nivel') == 'Gerente'): ?>
						<a href="pedidos/adicionar-pedido/<?php echo $cliente['id'] ?>"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="desc">Pedido</span></a>										
						<a href="clientes/editar-cliente/<?php echo $cliente['id'] ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><span class="desc">Editar</span></a>
						<a href="clientes/remover-cliente/<?php echo $status ?>/<?php echo $cliente['id'] ?>" onclick="return confirm('Deseja realmente remover esse registro?')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span><span class="desc">Remover</span></a>
					<?php endif ?>
					</td>
                </tr>
                <?php endforeach ?>
              </tbody>
            </table>
          </div>
          
        <?php if(!empty($paginacao)): ?>
          <nav class="paginacao">
            <?php echo $paginacao ?>
          </nav>
          <?php endif ?>
          
          <?php else: ?>
          <div class="vazio">
            <div class="alert alert-warning" role="alert">
              <strong>Ops!</strong> Não há registros com o status selecionado.
            </div>
          </div>
          <?php endif ?>
        </div>
      </div>
    </div>