<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="usuarios">Listar Usuarios <span class="sr-only">(atual)</span></a></li>
            <li><a href="usuarios/adicionar-usuario">Adicionar Usuário</a></li>
          </ul>          
        </div>
        
        
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Usuários
          <div class="pull-right">
            <a class="btn btn-success" href="usuarios/adicionar-usuario" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="desc">Adicionar Usuário</span></a>
          </div>
          <div class="clearfix"></div>
          </h1>
          
          <?php if ($this->session->flashdata('sucesso')): ?>
          <div class="alert alert-success" role="alert">
            <strong>Uhuuu!</strong> <?php echo $this->session->flashdata('sucesso'); ?>
          </div>
          <?php endif ?>
          
          <ul class="nav nav-tabs">
            <li role="presentation"<?php echo $status == 'ativos' ? ' class="active"' : '' ?>><a href="usuarios/">Ativos</a></li>
            <li role="presentation"<?php echo $status == 'inativos' ? ' class="active"' : '' ?>><a href="usuarios/listar-usuarios/inativos">Inativos</a></li>
            <li role="presentation"<?php echo $status == 'todos' ? ' class="active"' : '' ?>><a href="usuarios/listar-usuarios/todos">Todos</a></li>
          </ul>
          
          <?php if (count($usuarios) > 0): ?>
          
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>E-mail</th>
                  <th>Usuário</th>
                  <th>Data</th>
                  <?php if ($status == 'todos'): ?>
                  <th>Status</th>
                  <?php endif ?>
                  <th class="opcoes">Opções</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach ($usuarios as $usuario): ?>
                <tr>
                  <td><?php echo $usuario['nome'] ?></td>
                  <td><?php echo $usuario['email'] ?></td>
                  <td><?php echo $usuario['usuario'] ?></td>
                  <td><?php echo date('d/m/Y', strtotime($usuario['data'])) ?></td>
                  <?php if ($status == 'todos'): ?>
                  <td><?php echo $usuario['status'] ?></td>
                  <?php endif ?>
                  <td class="opcoes">
                    <a href="usuarios/editar-usuario/<?php echo $usuario['id'] ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><span class="desc">Editar</span></a>
                    <a href="usuarios/remover-usuario/<?php echo $status ?>/<?php echo $usuario['id'] ?>" onclick="return confirm('Deseja realmente remover esse registro?')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span><span class="desc">Remover</span></a>
                  </td>
                </tr>
                <?php endforeach ?>
              </tbody>
            </table>
          </div>
          
        <?php if(!empty($paginacao)): ?>
          <nav class="paginacao">
            <?php echo $paginacao ?>
          </nav>
          <?php endif ?>
          
          <?php else: ?>
          <div class="vazio">
            <div class="alert alert-warning" role="alert">
              <strong>Ops!</strong> Não há registros com o status selecionado.
            </div>
          </div>
          <?php endif ?>
        </div>
      </div>
    </div>