<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Corpsystem</title>
    <base href="<?php echo site_url() ?>"/>
    <link rel="icon" href="img/favicon.ico">
    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
<?php if(!empty($styles)): ?>
<?php foreach($styles as $style): ?>
    <link href="<?php echo $style ?>" rel="stylesheet">
<?php endforeach ?>
<?php endif ?>
    <script src="bootstrap/js/jquery/jquery-1.11.3.min.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <script src="js/libraries/jquery.mask.js"></script>
    <script src="js/script.js"></script>
<?php if(!empty($scripts)): ?>
<?php foreach($scripts as $script): ?>
    <script src="<?php echo $script ?>"></script>
<?php endforeach ?>
<?php endif ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if IE]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->      
  </head>
  <body>
    
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <?php if($this->session->userdata('login')): ?>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Navegar</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <?php endif ?>
          <a class="navbar-brand" href="<?php echo site_url() ?>"><img src="img/logo-login.png" width="130" height="29" alt="Corpsystem" /></a>
        </div>
        
        <?php if($this->session->userdata('login')): ?>
        <div id="navbar" class="navbar-collapse collapse">
          <form action="pesquisa" method="Post" class="navbar-form navbar-right">
            <input type="text" name="palavra" class="form-control" value="<?php echo $this->session->userdata('palavra') ?>" placeholder="Pesquisar...">
          </form>
          
          <ul class="nav navbar-nav navbar-right">
           
            <li><a href="pedidos"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><span class="desc">Pedidos</span></a></li>
            <li><a href="vendas"><span class="glyphicon glyphicon-tag" aria-hidden="true"></span><span class="desc">Vendas</span></a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span><span class="desc">Mais <span class="caret"></span></span></a>
                <ul class="dropdown-menu">                  
                  <li><a href="clientes">Clientes</a></li>
                  <li><a href="estoque">Produtos</a></li>                  
                  <li><a href="usuarios">Usuários</a></li>                  
                  <li><a href="login/sair">Sair</a></li>
                </ul>
          </li>
          </ul>
        </div>
        <?php endif ?>
      </div>
    </nav>
    <div id="conteudo">
    <?php echo $_content ?>
    </div>
  </body>
</html>