<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="estoque/listar-produtos">Listar Produtos <span class="sr-only">(atual)</span></a></li>
          </ul>          
        </div>
        
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Estoque</h1>
          
          <?php if (validation_errors()): ?>
          <div class="alert alert-danger" role="alert">
            <strong>Hmmm!</strong> Alguns erros foram encontrados...
          </div>
          <?php endif ?>
          
          <?php if ($this->session->flashdata('sucesso')): ?>
          <div class="alert alert-success" role="alert">
            <strong>Uhuuu!</strong> <?php echo $this->session->flashdata('sucesso'); ?>
          </div>
          <?php endif ?>
          
          <?php if ($this->session->flashdata('falha')): ?>
          <div class="alert alert-danger" role="alert">
            <strong>Hmmm!</strong> <?php echo $this->session->flashdata('falha'); ?>
          </div>
          <?php endif ?>
          <form action="estoque/listar-produtos" name="festoque" id="festoque" method="Post" enctype="multipart/form-data">
                  
            <div class="table-responsive">
              <table class="table table-striped">
                <tr>
                    <th>Categoria</th>
                    <th>SKU</th>
                    <th>Modelo</th>
                    <th>Qtde.</th>
                    <th>V. Bruto</th>
                    <th>V. Venda</th>
                  </tr> 
                  <tr>
                    <td>
                        <div class="form-group<?php echo form_error('categoria') ? ' has-error' : '' ?>">
                            <select class="form-control" name="categoria" id="categoria">
                                <option value=""<?php echo set_select('categoria', '', true) ?>>- Categoria -</option>
                                <option value="Cat-A"<?php echo set_select('categoria', 'Cat-A') ?>>Cat-A</option>
                                <option value="Cat-B"<?php echo set_select('categoria', 'Cat-B') ?>>Cat-B</option> 
								<option value="Cat-C"<?php echo set_select('categoria', 'Cat-C') ?>>Cat-C</option>								
                            </select>
                        </div>
                      </td>
                      <td width="80">
                        <div class="form-group<?php echo form_error('codigo') ? ' has-error' : '' ?>">
                            <input type="text" class="form-control tamanho-codigo" name="codigo" id="codigo" placeholder="NNN9999" maxlength="7" value="<?php echo set_value('codigo'); ?>">
                        </div>
                      </td>
                      <td>
                        <div class="form-group<?php echo form_error('modelo') ? ' has-error' : '' ?>">
                            <input type="text" class="form-control tamanho-modelo" name="modelo" placeholder="Modelo" value="<?php echo set_value('modelo'); ?>">
                        </div>
                      </td>
                      
                      <td>
                        <div class="form-group<?php echo form_error('quantidade') ? ' has-error' : '' ?>">
                            <input type="number" class="form-control" name="quantidade" placeholder="0" value="<?php echo set_value('quantidade') ?>">
                        </div>
                      </td>
                      <?php if($this->session->userdata('nivel') == 'Administrador' ||
                               $this->session->userdata('nivel') == 'Gerente'): ?>
                      <td>
                        <div class="form-group<?php echo form_error('bruto') ? ' has-error' : '' ?>">
                            <input type="text" class="form-control valor" name="bruto" placeholder="0,00" value="<?php echo set_value('bruto') ?>">
                        </div>
                      </td>
                      <?php endif ?>
                      <td>
                        <div class="form-group<?php echo form_error('valor') ? ' has-error' : '' ?>">
                            <input type="text" class="form-control valor" name="valor" placeholder="0,00" value="<?php echo set_value('valor') ?>">
                        </div>
                      </td>
                  </tr>
                  <tr>
                    <td colspan="2">
                        <div class="form-group">
                            <input type="file" name="imagem" accept="image/*" class="form-control">
                        </div>
                    </td>
                    <td colspan="4">
                        <div class="form-group<?php echo form_error('descricao') ? ' has-error' : '' ?>">
                            <textarea name="descricao" class="form-control" rows="3" placeholder="Descrição"><?php echo set_value('descricao') ?></textarea>
                        </div>
                    </td>
                  </tr>
            
              </table>
              <div class="pull-right">
                <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Adicionar</button>
              </div>
              <div class="clearfix"></div>
                
            </div>
            </form>
          
          
            <?php if (count($produtos) > 0): ?>
            <ul class="nav nav-tabs">
            <?php $c = 0; foreach ($produtos as $categoria => $itens): $c++; ?>
                <li role="presentation" <?php echo $c == 1 ? 'class="active" ' : '' ?>role="tablist"><a href="#<?php echo $categoria ?>" aria-controls="<?php echo $categoria ?>" role="tab" data-toggle="tab"><?php echo $categoria ?></a></li>
            <?php endforeach ?>
              </ul>
            
            <div class="tab-content">
            <?php $c = 0;  foreach ($produtos as $categoria => $itens): $c++;  ?>
           
            <div role="tabpanel" class="tab-pane<?php echo $c == 1 ? ' active ' : '' ?>" id="<?php echo $categoria ?>">
                
            <div class="table-responsive">
            <table class="table table-striped">
            <thead>
                    <tr>
                        <th width="3"></th>
                        <th>Imagem</th>
                        <th>Código</th>
                        <th width="280">Modelo / Descrição</th>
                        <th>Qtde.</th>
                        <?php if($this->session->userdata('nivel') == 'Administrador' ||
                                 $this->session->userdata('nivel') == 'Gerente'): ?>
                        <th>V. Bruto</th>
                        <?php endif ?>
                        <th>V. Venda</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
            
            <?php foreach ($itens as $produto): ?>
                    <tr<?php echo $produto['status'] == 'Inativo' ? ' class="inativo"' : '' ?>>
                        <td class="<?php echo $produto['status'] == 'Ativo' ? 'bg-verde' : 'bg-vermelho' ?>"></td>
                        <td>
                            <?php if(!empty($produto['imagem'])): ?>
                             <a href="<?php echo site_url($produto['imagem']) ?>" target="_blank"><img src="<?php echo $produto['imagem'] ?>" height="80" width="80"></a>
                            <?php else: ?>
                            <span class="no-img"><span class="glyphicon glyphicon-picture"></span></span>
                            <?php endif ?>
                        </td>
                        <td><strong><?php echo $produto['codigo'] ?></strong></td>
                        <td><?php echo $produto['modelo'] ? $produto['modelo'] : '--' ?>
                            <?php if($produto['descricao']): ?>
                            <br><span class="itens"><?php echo nl2br($produto['descricao']) ?></span>
                            <?php endif ?>
                        </td>
                        <td>
                            <?php if ($produto['status'] == 'Ativo'): ?>
                            <input type="number" name="quantidade" class="form-control estoque-quantidade" data-id="<?php echo $produto['id'] ?>" value="<?php echo $produto['quantidade'] ?>">
                            <?php else: ?>
                            <?php echo $produto['quantidade'] ?>
                            <?php endif ?>
                        </td>
                        <?php if($this->session->userdata('nivel') == 'Administrador' ||
                                 $this->session->userdata('nivel') == 'Gerente'): ?>
                        <td>
                            <?php if ($produto['status'] == 'Ativo'): ?>
                            <input type="text" name="bruto" class="form-control valor estoque-bruto" data-id="<?php echo $produto['id'] ?>" value="<?php echo number_format($produto['bruto'], 2, ',', '') ?>">
                            <?php else: ?>
                            R$ <?php echo number_format($produto['bruto'], 2, ',', '') ?>
                            <?php endif ?>
                        </td>
                        <?php endif ?>
                        <td>
                            <?php if ($produto['status'] == 'Ativo'): ?>
                            <input type="text" name="valor" class="form-control valor estoque-valor" data-id="<?php echo $produto['id'] ?>" value="<?php echo number_format($produto['valor'], 2, ',', '') ?>">
                            <?php else: ?>
                            R$ <?php echo number_format($produto['valor'], 2, ',', '') ?>
                            <?php endif ?>
                        </td>
                        <td class="opcoes">
                            <a href="estoque/editar-produto/<?php echo $produto['id'] ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><span class="desc">Editar</span></a>
                            
                            <?php if ($produto['status'] == 'Ativo'): ?>
                            <a href="estoque/desabilitar-produto/<?php echo $produto['id'] ?>"><span class="glyphicon glyphicon-stop" aria-hidden="true"></span><span class="desc">Desabilitar</span></a>
                            <?php else: ?>
                            <a href="estoque/habilitar-produto/<?php echo $produto['id'] ?>"><span class="glyphicon glyphicon-play" aria-hidden="true"></span><span class="desc">Habilitar</span></a>
                            <?php endif ?>
                            <?php if($this->session->userdata('nivel') == 'Administrador' ||
                                 $this->session->userdata('nivel') == 'Gerente'): ?>
                            <a href="estoque/excluir-produto/<?php echo $produto['id'] ?>" onclick="return confirm('Deseja realmente remover esse registro?')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span><span class="desc">Remover</span></a>
                            <?php endif ?>
                        </td>
                    </tr>
            <?php endforeach ?>
            
                    
                </tbody>
            </table>
          </div>
            </div>
            
            <?php endforeach ?>
          </div>
          <?php endif ?>  
            
          <?php if(!empty($paginacao)): ?>
          <nav class="paginacao">
            <?php echo $paginacao ?>
          </nav>
          <?php endif ?>

        </div>
    </div>
</div>