<div class="container-fluid">
    <div class="row">
        <div class="main">
            <h1 class="page-header">Resultado</h1>
            
            <?php if (count($resultado) > 0): ?>
            
            <ul class="nav nav-tabs">
                <?php foreach ($tabelas as $item): ?>
                <li role="presentation"<?php echo $tabela == $item ? ' class="active"' : '' ?>><a href="pesquisa/listar-resultado/<?php echo $item ?>"><?php echo $nomes[$item] ?></a></li>
                <?php endforeach ?>
            </ul>
        
            <!-- Pesquisa em Clientes -->
			<?php if($tabela == 'clientes'): ?>
            <div class="table-responsive">              
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th>N.</th>
                    <th>Cliente</a></th>
                    <th>E-mail</th>
                    <th>Telefone</th>
                    <th>CEP</th>
                    <th>Data</th>
                    <th>Origem</th>
                    <th class="opcoes">Opções</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($resultado as $cliente): ?>
                  <tr>
                    <td><?php echo $cliente['id'] ?></td>
                    <td><?php echo $cliente['cliente'] ?></td>
                    <td><?php echo $cliente['email'] ? $cliente['email'] : '--' ?></td>
                    <td><?php echo $cliente['telefone'] ? $cliente['telefone'] : '--'  ?></td>
                    <td><?php echo $cliente['cep'] ? $cliente['cep'] : '--'  ?></td>                   
                    <td><?php echo date('d/m/Y', strtotime($cliente['data'])) ?></td>
                    <td><?php echo $cliente['origem'] ?></td>
                    <td class="opcoes">
                    <?php if($this->session->userdata('nivel') == 'Administrador' || $this->session->userdata('nivel') == 'Gerente'): ?>
                      <a href="pedidos/adicionar-pedido/<?php echo $cliente['id'] ?>"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="desc">Novo Pedido</span></a>                    
                      <a href="clientes/editar-cliente/<?php echo $cliente['id'] ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><span class="desc">Editar</span></a>
                      <a href="clientes/remover-cliente/<?php echo $cliente['status'] ?>/<?php echo $cliente['id'] ?>" onclick="return confirm('Deseja realmente remover esse registro?')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span><span class="desc">Remover</span></a>
                      <?php endif ?>
                    </td>
                  </tr>
                  <?php endforeach ?>
                </tbody>
              </table>
            </div>
            <?php endif ?>              
            <!--.\ End Pesquisa em Clientes -->
			
			<!-- Pesquisa em Pedidos -->
            <?php if($tabela == 'pedidos'): ?>
            <div class="table-responsive">
                <table class="table table-striped">
                <thead>
                  <tr>
                    <th>N.</th>
                    <th>Cliente</th>                  
                    <th>Total</th>
                    <th>Entrega</th>
                    <th>Rastreio</th>
                    <th>Origem</th>
                    <th>Status</th>
                    <th>Data</th>
                    <th class="opcoes">Opções</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($resultado as $pedido): ?>
                  <?php $c = 0; $itens  = ''; foreach ($pedido['itens'] as $item): $c++ ?>
                          <?php $itens .= $item['item'] ?>
                          <?php $itens .= $c < count($pedido['itens']) ? ', ' : '.' ?>
                  <?php endforeach ?>
                  <tr>
                    <td><?php echo $pedido['id'] ?></td> 
                    <td>
                          <span data-toggle="tooltip" title="<?php echo character_limiter($itens, 125) ?>">
                          <?php echo $pedido['cliente'] ?>
                          <span class="itens">
                          <?php echo character_limiter($itens, 25) ?>
                          </span>
                          </span>
                    </td>                  
                    <td><?php echo $pedido['total'] ? 'R$ '. number_format($pedido['total'], 2, ',', '.') : '--'  ?></td>
                    <td><?php echo $pedido['postagem'] ?></td>
                    <td><?php echo $pedido['rastreio'] ? $pedido['rastreio'] : '--'  ?></td>
                    <td><?php echo $pedido['origem'] ? $pedido['origem'] : '--'  ?></td>             
                    <td><?php echo $pedido['status'] ? $pedido['status'] : '--'  ?></td>
                    <td><?php echo date('d/m/Y', strtotime($pedido['data'])) ?></td>
                    <td class="opcoes">
                      <a href="pedidos/ver-pedido/<?php echo $pedido['cliente_id'] ?>/<?php echo $pedido['id'] ?>"><span class="glyphicon glyphicon-search" aria-hidden="true"></span><span class="desc">Ver</span></a>                    
                      <?php if($this->session->userdata('nivel') == 'Administrador' || $this->session->userdata('nivel') == 'Gerente'): ?>
                      <a href="pedidos/editar-pedido/<?php echo $pedido['id'] ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><span class="desc">Editar</span></a>
                      <a href="pedidos/remover-pedido/pendente/<?php echo $pedido['id'] ?>" onclick="return confirm('Deseja realmente remover esse registro?')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span><span class="desc">Remover</span></a>
                      <?php endif ?>
                    </td>
                  </tr>
                  <?php endforeach ?>
                </tbody>
              </table>
            </div>        
            <?php endif ?>
			<!--\. End Pesquisa em Pedidos -->			
            
            <!-- Pesquisa em Vendas -->
			<?php if($tabela == 'vendas'): ?>
            <div class="table-responsive">
                <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Imagem</th>
                    <th>Cliente</th>
                    <th>Código</th>
                    <th width="280">Modelo / Descrição</th>
                    <th width="150">Qtde.</th>
                    <th>Valor</th>
                    <th>Subtotal</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                  <?php foreach ($resultado as $venda): ?>
                  <?php $c = 0; $itens  = ''; foreach ($venda['itens'] as $item): $c++ ?>
                          <?php $itens .= $item['codigo'] ?>
                          <?php $itens .= $c < count($venda['itens']) ? ', ' : '.' ?>
                  <?php endforeach ?>
                  <tr>
                    <td>
                        <?php if(!empty($venda['imagem'])): ?>
                        <a href="<?php echo site_url($venda['imagem']) ?>" target="_blank"><img src="<?php echo $venda['imagem'] ?>" height="80" width="80"></a>
                        <?php else: ?>
                        <span class="no-img"><span class="glyphicon glyphicon-picture"></span></span>
                        <?php endif ?>
                    </td>
                    <td><a href="clientes/historico/<?php echo $venda['cliente_id'] ?>"><?php echo $venda['cliente'] ?></a></td>
                    <td><strong><?php echo $venda['codigo'] ?></strong></td>
                    <td><?php echo !empty($venda['modelo']) ? $venda['modelo'] : '--' ?>
                        <?php if (!empty($venda['descricao'])): ?>
                        <br><span class="itens"><?php echo nl2br($venda['descricao']) ?></span>
                        <?php endif ?>
                    </td>
                    <td><?php echo $venda['quantidade'] ?></td>
                    <td>R$ <?php echo number_format($venda['valor'], 2, ',', '.') ?></td>
                    <td>R$ <?php echo number_format($venda['valor'] * $venda['quantidade'], 2, ',', '.') ?></td>
                    <td><?php echo $venda['status'] ?></td>
                </tr>
                  <?php endforeach ?>
                </tbody>
              </table>
            </div>        
            <?php endif ?>
			<!--\. End Pesquisa em Vendas -->
            
            <?php if(!empty($paginacao)): ?>
            <nav class="paginacao">
              <?php echo $paginacao ?>
            </nav>
            <?php endif ?>
              
              
            <?php else: ?>
            <div class="vazio">
              <div class="alert alert-warning" role="alert">
                <strong>Ops!</strong> Não há resultados para o termo pesquisado.
              </div>
            </div>
            <?php endif ?>
        </div>
    </div>
</div>